[package]
name = "hyperspace-store"
version = "0.1.0"
edition = "2021"

[dependencies]
memmap2 = { workspace = true }
thiserror = { workspace = true }
hyperspace-core = { workspace = true }
byteorder = "1.5.0"
parking_lot.workspace = true

[dev-dependencies]
tempfile = "3.8"
