[package]
name = "hyperspace-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = { workspace = true }
crossterm = "0.27"
tokio = { workspace = true }
hyperspace-proto = { workspace = true }
hyperspace-core = { workspace = true }
