[book]
authors = ["YARlabs"]
language = "en"

src = "src"
title = "HyperspaceDB Documentation"

[output.html]
mathjax-support = true
default-theme = "navy"
site-url = "/hyperspace-db/"
git-repository-url = "https://github.com/yarlabs/hyperspace-db"
